// <auto-generated />
using System;
using AspNetCore.Profiler.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspNetCore.Profiler.Dal.Migrations
{
    [DbContext(typeof(DemoDbContext))]
    [Migration("20240826164842_InitCreate")]
    partial class InitCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AspNetCore.Profiler.Dal.Models.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1);

                    b.Property<decimal>("Amount")
                        .HasColumnType("DECIMAL(18,0)");

                    b.Property<DateTimeOffset>("CreateOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Item")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("AspNetCore.Profiler.Dal.Models.Table", b =>
                {
                    b.Property<string>("TableCatalog")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TABLE_CATALOG");

                    b.Property<string>("TableName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TABLE_NAME");

                    b.Property<string>("TableSchema")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TABLE_SCHEMA");

                    b.Property<string>("TableType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TABLE_TYPE");

                    b.ToTable("Tables", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
